In [1]:
#Import the libraries
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
crime=pd.read_csv(r"C:\Users\ADITYA\Desktop\EXCELR ASSIGNMENT\CLUSTERING\crime_data.csv")

In [4]:
crime.head()

Unnamed: 0  Murder  Assault  UrbanPop  Rape
0     Alabama    13.2      236        58  21.2
1      Alaska    10.0      263        48  44.5
2     Arizona     8.1      294        80  31.0
3    Arkansas     8.8      190        50  19.5
4  California     9.0      276        91  40.6

In [5]:
crime1=crime.iloc[:,1:]

In [6]:
crime1

Murder  Assault  UrbanPop  Rape
0     13.2      236        58  21.2
1     10.0      263        48  44.5
2      8.1      294        80  31.0
3      8.8      190        50  19.5
4      9.0      276        91  40.6
5      7.9      204        78  38.7
6      3.3      110        77  11.1
7      5.9      238        72  15.8
8     15.4      335        80  31.9
9     17.4      211        60  25.8
10     5.3       46        83  20.2
11     2.6      120        54  14.2
12    10.4      249        83  24.0
13     7.2      113        65  21.0
14     2.2       56        57  11.3
15     6.0      115        66  18.0
16     9.7      109        52  16.3
17    15.4      249        66  22.2
18     2.1       83        51   7.8
19    11.3      300        67  27.8
20     4.4      149        85  16.3
21    12.1      255        74  35.1
22     2.7       72        66  14.9
23    16.1      259        44  17.1
24     9.0      178        70  28.2
25     6.0      109        53  16.4
26     4.3      102        62  16.5
27    12.2      252        81  46.0
28     2.1       57        56   9.5
29     7.4      159        89  18.8
30    11.4      285        70  32.1
31    11.1      254        86  26.1
32    13.0      337        45  16.1
33     0.8       45        44   7.3
34     7.3      120        75  21.4
35     6.6      151        68  20.0
36     4.9      159        67  29.3
37     6.3      106        72  14.9
38     3.4      174        87   8.3
39    14.4      279        48  22.5
40     3.8       86        45  12.8
41    13.2      188        59  26.9
42    12.7      201        80  25.5
43     3.2      120        80  22.9
44     2.2       48        32  11.2
45     8.5      156        63  20.7
46     4.0      145        73  26.2
47     5.7       81        39   9.3
48     2.6       53        66  10.8
49     6.8      161        60  15.6

In [9]:
std_df = StandardScaler().fit_transform(crime1)
std_df

array([[ 1.25517927,  0.79078716, -0.52619514, -0.00345116],
       [ 0.51301858,  1.11805959, -1.22406668,  2.50942392],
       [ 0.07236067,  1.49381682,  1.00912225,  1.05346626],
       [ 0.23470832,  0.23321191, -1.08449238, -0.18679398],
       [ 0.28109336,  1.2756352 ,  1.77678094,  2.08881393],
       [ 0.02597562,  0.40290872,  0.86954794,  1.88390137],
       [-1.04088037, -0.73648418,  0.79976079, -1.09272319],
       [-0.43787481,  0.81502956,  0.45082502, -0.58583422],
       [ 1.76541475,  1.99078607,  1.00912225,  1.1505301 ],
       [ 2.22926518,  0.48775713, -0.38662083,  0.49265293],
       [-0.57702994, -1.51224105,  1.21848371, -0.11129987],
       [-1.20322802, -0.61527217, -0.80534376, -0.75839217],
       [ 0.60578867,  0.94836277,  1.21848371,  0.29852525],
       [-0.13637203, -0.70012057, -0.03768506, -0.0250209 ],
       [-1.29599811, -1.39102904, -0.5959823 , -1.07115345],
       [-0.41468229, -0.67587817,  0.03210209, -0.34856705],
       [ 0.44344101, -0.

In [17]:
#dbscan = DBSCAN(eps=0.5, min_samples=12)
dbscan = DBSCAN(eps=1, min_samples=4)
dbscan.fit(std_df)

DBSCAN(eps=1, min_samples=4)

In [18]:
dbscan.labels_

array([ 0, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1,  1,  1,  1,  1,
        0,  1, -1,  1, -1,  1, -1,  1,  1,  1, -1,  1,  1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  0,  1,  0, -1,  1,  1,  1,  1,  1,  1,  1],
      dtype=int64)

In [19]:
cl=pd.DataFrame(dbscan.labels_,columns=['cluster'])

In [20]:
cl

cluster
0         0
1        -1
2        -1
3        -1
4        -1
5        -1
6         1
7        -1
8        -1
9        -1
10       -1
11        1
12       -1
13        1
14        1
15        1
16        1
17        0
18        1
19       -1
20        1
21       -1
22        1
23       -1
24        1
25        1
26        1
27       -1
28        1
29        1
30       -1
31       -1
32       -1
33        1
34        1
35        1
36        1
37        1
38        1
39        0
40        1
41        0
42       -1
43        1
44        1
45        1
46        1
47        1
48        1
49        1

In [24]:
clustered = pd.concat([crime,cl],axis=1)

In [25]:
clustered

Unnamed: 0  Murder  Assault  UrbanPop  Rape  cluster
0          Alabama    13.2      236        58  21.2        0
1           Alaska    10.0      263        48  44.5       -1
2          Arizona     8.1      294        80  31.0       -1
3         Arkansas     8.8      190        50  19.5       -1
4       California     9.0      276        91  40.6       -1
5         Colorado     7.9      204        78  38.7       -1
6      Connecticut     3.3      110        77  11.1        1
7         Delaware     5.9      238        72  15.8       -1
8          Florida    15.4      335        80  31.9       -1
9          Georgia    17.4      211        60  25.8       -1
10          Hawaii     5.3       46        83  20.2       -1
11           Idaho     2.6      120        54  14.2        1
12        Illinois    10.4      249        83  24.0       -1
13         Indiana     7.2      113        65  21.0        1
14            Iowa     2.2       56        57  11.3        1
15          Kansas     6.0      115        66  18.0        1
16        Kentucky     9.7      109        52  16.3        1
17       Louisiana    15.4      249        66  22.2        0
18           Maine     2.1       83        51   7.8        1
19        Maryland    11.3      300        67  27.8       -1
20   Massachusetts     4.4      149        85  16.3        1
21        Michigan    12.1      255        74  35.1       -1
22       Minnesota     2.7       72        66  14.9        1
23     Mississippi    16.1      259        44  17.1       -1
24        Missouri     9.0      178        70  28.2        1
25         Montana     6.0      109        53  16.4        1
26        Nebraska     4.3      102        62  16.5        1
27          Nevada    12.2      252        81  46.0       -1
28   New Hampshire     2.1       57        56   9.5        1
29      New Jersey     7.4      159        89  18.8        1
30      New Mexico    11.4      285        70  32.1       -1
31        New York    11.1      254        86  26.1       -1
32  North Carolina    13.0      337        45  16.1       -1
33    North Dakota     0.8       45        44   7.3        1
34            Ohio     7.3      120        75  21.4        1
35        Oklahoma     6.6      151        68  20.0        1
36          Oregon     4.9      159        67  29.3        1
37    Pennsylvania     6.3      106        72  14.9        1
38    Rhode Island     3.4      174        87   8.3        1
39  South Carolina    14.4      279        48  22.5        0
40    South Dakota     3.8       86        45  12.8        1
41       Tennessee    13.2      188        59  26.9        0
42           Texas    12.7      201        80  25.5       -1
43            Utah     3.2      120        80  22.9        1
44         Vermont     2.2       48        32  11.2        1
45        Virginia     8.5      156        63  20.7        1
46      Washington     4.0      145        73  26.2        1
47   West Virginia     5.7       81        39   9.3        1
48       Wisconsin     2.6       53        66  10.8        1
49         Wyoming     6.8      161        60  15.6        1

In [26]:
clustered.groupby('cluster').agg(['mean'])

C:\Users\ADITYA\AppData\Local\Temp\ipykernel_3628\3663253137.py:1: FutureWarning: ['Unnamed: 0'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  clustered.groupby('cluster').agg(['mean'])


Murder     Assault   UrbanPop       Rape
              mean        mean       mean       mean
cluster                                             
-1       11.005556  247.166667  70.666667  28.766667
 0       14.050000  238.000000  57.750000  23.200000
 1        4.825000  112.035714  63.357143  16.107143

In [28]:
clustered['cluster'].value_counts()

 1    28
-1    18
 0     4
Name: cluster, dtype: int64

In [30]:

clustered[clustered.cluster == -1]

Unnamed: 0  Murder  Assault  UrbanPop  Rape  cluster
1           Alaska    10.0      263        48  44.5       -1
2          Arizona     8.1      294        80  31.0       -1
3         Arkansas     8.8      190        50  19.5       -1
4       California     9.0      276        91  40.6       -1
5         Colorado     7.9      204        78  38.7       -1
7         Delaware     5.9      238        72  15.8       -1
8          Florida    15.4      335        80  31.9       -1
9          Georgia    17.4      211        60  25.8       -1
10          Hawaii     5.3       46        83  20.2       -1
12        Illinois    10.4      249        83  24.0       -1
19        Maryland    11.3      300        67  27.8       -1
21        Michigan    12.1      255        74  35.1       -1
23     Mississippi    16.1      259        44  17.1       -1
27          Nevada    12.2      252        81  46.0       -1
30      New Mexico    11.4      285        70  32.1       -1
31        New York    11.1      254        86  26.1       -1
32  North Carolina    13.0      337        45  16.1       -1
42           Texas    12.7      201        80  25.5       -1

Airline

In [32]:
airline=pd.read_csv(r"C:\Users\ADITYA\Desktop\EXCELR ASSIGNMENT\CLUSTERING\EastWestAirlines1.csv")

In [33]:
airline

ID#  Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0        1    28143           0          1          1          1          174   
1        2    19244           0          1          1          1          215   
2        3    41354           0          1          1          1         4123   
3        4    14776           0          1          1          1          500   
4        5    97752           0          4          1          1        43300   
...    ...      ...         ...        ...        ...        ...          ...   
3994  4017    18476           0          1          1          1         8525   
3995  4018    64385           0          1          1          1          981   
3996  4019    73597           0          3          1          1        25447   
3997  4020    54899           0          1          1          1          500   
3998  4021     3016           0          1          1          1            0   

      Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  \
0               1                  0                0               7000   
1               2                  0                0               6968   
2               4                  0                0               7034   
3               1                  0                0               6952   
4              26               2077                4               6935   
...           ...                ...              ...                ...   
3994            4                200                1               1403   
3995            5                  0                0               1395   
3996            8                  0                0               1402   
3997            1                500                1               1401   
3998            0                  0                0               1398   

      Award?  
0          0  
1          0  
2          0  
3          0  
4          1  
...      ...  
3994       1  
3995       1  
3996       1  
3997       0  
3998       0  

[3999 rows x 12 columns]

In [34]:
airline1=airline.iloc[:,1:]

In [35]:
airline1

Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0       28143           0          1          1          1          174   
1       19244           0          1          1          1          215   
2       41354           0          1          1          1         4123   
3       14776           0          1          1          1          500   
4       97752           0          4          1          1        43300   
...       ...         ...        ...        ...        ...          ...   
3994    18476           0          1          1          1         8525   
3995    64385           0          1          1          1          981   
3996    73597           0          3          1          1        25447   
3997    54899           0          1          1          1          500   
3998     3016           0          1          1          1            0   

      Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  \
0               1                  0                0               7000   
1               2                  0                0               6968   
2               4                  0                0               7034   
3               1                  0                0               6952   
4              26               2077                4               6935   
...           ...                ...              ...                ...   
3994            4                200                1               1403   
3995            5                  0                0               1395   
3996            8                  0                0               1402   
3997            1                500                1               1401   
3998            0                  0                0               1398   

      Award?  
0          0  
1          0  
2          0  
3          0  
4          1  
...      ...  
3994       1  
3995       1  
3996       1  
3997       0  
3998       0  

[3999 rows x 11 columns]

In [36]:
# standardizing the data 
airlines_norm = StandardScaler().fit_transform(airline1)
airlines_norm

array([[-4.51140783e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01,  1.39545434e+00, -7.66919299e-01],
       [-5.39456874e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01,  1.37995704e+00, -7.66919299e-01],
       [-3.20031232e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01,  1.41192021e+00, -7.66919299e-01],
       ...,
       [-4.29480975e-05, -1.86298687e-01,  6.83121167e-01, ...,
        -3.62167870e-01, -1.31560393e+00,  1.30391816e+00],
       [-1.85606976e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -9.85033311e-02, -1.31608822e+00, -7.66919299e-01],
       [-7.00507951e-01, -1.86298687e-01, -7.69578406e-01, ...,
        -3.62167870e-01, -1.31754109e+00, -7.66919299e-01]])

In [46]:

dbscan = DBSCAN(eps=2, min_samples=22)
dbscan.fit(airlines_norm)

DBSCAN(eps=2, min_samples=22)

In [39]:
dbscan.labels_

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [40]:
cl=pd.DataFrame(dbscan.labels_,columns=['cluster'])

In [41]:
clustered = pd.concat([airline,cl],axis=1)

In [42]:
clustered

ID#  Balance  Qual_miles  cc1_miles  cc2_miles  cc3_miles  Bonus_miles  \
0        1    28143           0          1          1          1          174   
1        2    19244           0          1          1          1          215   
2        3    41354           0          1          1          1         4123   
3        4    14776           0          1          1          1          500   
4        5    97752           0          4          1          1        43300   
...    ...      ...         ...        ...        ...        ...          ...   
3994  4017    18476           0          1          1          1         8525   
3995  4018    64385           0          1          1          1          981   
3996  4019    73597           0          3          1          1        25447   
3997  4020    54899           0          1          1          1          500   
3998  4021     3016           0          1          1          1            0   

      Bonus_trans  Flight_miles_12mo  Flight_trans_12  Days_since_enroll  \
0               1                  0                0               7000   
1               2                  0                0               6968   
2               4                  0                0               7034   
3               1                  0                0               6952   
4              26               2077                4               6935   
...           ...                ...              ...                ...   
3994            4                200                1               1403   
3995            5                  0                0               1395   
3996            8                  0                0               1402   
3997            1                500                1               1401   
3998            0                  0                0               1398   

      Award?  cluster  
0          0        0  
1          0        0  
2          0        0  
3          0        0  
4          1        1  
...      ...      ...  
3994       1        1  
3995       1        1  
3996       1        1  
3997       0        0  
3998       0        0  

[3999 rows x 13 columns]

In [43]:
clustered.groupby('cluster').agg(['mean'])

ID#        Balance   Qual_miles cc1_miles cc2_miles  \
                mean           mean         mean      mean      mean   
cluster                                                                
-1       1765.599327  205612.959596  1433.723906  2.569024  1.195286   
 0       2176.183690   57252.671334    30.025535  1.693575  1.000000   
 1       1765.389325   73983.653061    60.907378  2.638148  1.000000   

        cc3_miles   Bonus_miles Bonus_trans Flight_miles_12mo Flight_trans_12  \
             mean          mean        mean              mean            mean   
cluster                                                                         
-1       1.164983  43338.360269   24.020202       2883.043771        8.340067   
 0       1.000000   9727.007414    8.845552        183.242586        0.542834   
 1       1.000000  25175.489011   13.959969        422.751962        1.332810   

        Days_since_enroll   Award?  
                     mean     mean  
cluster                             
-1            4631.006734  0.69697  
 0            3813.399094  0.00000  
 1            4580.672684  1.00000

In [45]:
clustered['cluster'].value_counts()

 0    2428
 1    1274
-1     297
Name: cluster, dtype: int64