In [1]:
import numpy as np
import scipy.stats as stats
import pandas as pd
import scipy as sp

from scipy.stats import ttest_1samp, ttest_ind, ttest_rel

     A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.


H0:THERE IS NO SIGNIFICANT DIFFERENCE BETWEEN UNIT A AND UNIT B
    
H1:THERE HAVE SIGNIFICANT DIFFERENCE BETWEEN UNIT A AND UNIT B

In [2]:
cutlets=pd.read_csv(r"C:\Users\ADITYA\Desktop\EXCELR ASSIGNMENT\Hypothesis\Cutlets.csv")

In [3]:
cutlets.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [4]:
cutlets.shape

(35, 2)

In [5]:
cutlets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Unit A  35 non-null     float64
 1   Unit B  35 non-null     float64
dtypes: float64(2)
memory usage: 688.0 bytes


In [6]:
cutlets.describe()

Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [7]:
unitA=cutlets['Unit A']
unitB=cutlets['Unit B']

In [8]:

unitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [9]:
ttest_ind(unitA, unitB,alternative='two-sided')


Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [10]:
 pvalue=0.4722394724599501

In [11]:
if pvalue  < 0.05:
    print ('A REJECT NULL HYPOTHESIS' )
else:
    
    print( 'WE REJECT TO FAIL NULL HYPOTHESIS')


WE REJECT TO FAIL NULL HYPOTHESIS


RESULT
THERE IS NO SIGNIFICANT DIFFERENCE BETWEEN UNIT A AND UNIT B

The Null and Alternative Hypothesis

H0:There are no significant differences between the groups' mean Lab values. 

H1:There is a significant difference between the groups' mean Lab values

In [12]:
lab=pd.read_csv(r"C:\Users\ADITYA\Desktop\EXCELR ASSIGNMENT\Hypothesis\LabTAT.csv")

In [13]:
lab.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [14]:
lab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laboratory 1  120 non-null    float64
 1   Laboratory 2  120 non-null    float64
 2   Laboratory 3  120 non-null    float64
 3   Laboratory 4  120 non-null    float64
dtypes: float64(4)
memory usage: 3.9 KB


In [15]:
lab.shape

(120, 4)

In [16]:
lab.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [17]:
lab1=lab["Laboratory 1"]
lab2=lab["Laboratory 2"]
lab3=lab["Laboratory 3"]
lab4=lab["Laboratory 4"]


In [18]:
lab4

0      166.13
1      160.79
2      185.18
3      176.42
4      152.60
        ...  
115    172.68
116    177.64
117    170.27
118    150.87
119    162.21
Name: Laboratory 4, Length: 120, dtype: float64

In [19]:
stats.f_oneway(lab1,lab2,lab3,lab4)

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [20]:
labpvalue=2.1156708949992414e-57

In [21]:
if labpvalue  < 0.05:
    print ('A REJECT NULL HYPOTHESIS' )
else:
    
    print( 'WE REJECT TO FAIL NULL HYPOTHESIS')

A REJECT NULL HYPOTHESIS


In [ ]:
# There is a significant difference between the groups' mean Lab values

Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions

In [ ]:
# H0:There is no difference between Sales of products in four different regions is tabulated for males and females
#H1:have significant difference between Sales of products in four different regions is tabulated for males and females.

In [23]:
buyer_rations=pd.read_csv(r"C:\Users\ADITYA\Desktop\EXCELR ASSIGNMENT\Hypothesis\BuyerRatio.csv")

In [24]:
buyer_rations

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [26]:
buyer_rations.describe()

East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

In [30]:
sales=buyer_rations.iloc[0:,1:5]

In [33]:
sales=sales.values

In [34]:
sales

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [51]:
stat, p, dof, expected = stats.chi2_contingency(sales)
print('dof=%d' % dof)
print('p=%f'%p)
print('stat=%f'%stat)
print(expected)

dof=3
p=0.660309
stat=1.595946
[[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [57]:

p=0.660309

In [59]:
if p< 0.05:
    print ('A REJECT NULL HYPOTHESIS' )
else:
    
    print( 'WE REJECT TO FAIL NULL HYPOTHESIS')

WE REJECT TO FAIL NULL HYPOTHESIS


#have significant difference between Sales of products in four different regions is tabulated for males and females.

#TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences


#H0:there is no  defective %  varies by centre
#H1: There is defective % varies by center

In [61]:
customer=pd.read_csv(r"C:\Users\ADITYA\Desktop\EXCELR ASSIGNMENT\Hypothesis\Costomer+OrderForm.csv")

In [62]:
customer.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [64]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB


In [65]:
customer.describe()

Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [73]:
customer.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [74]:
customer.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [75]:
customer.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [76]:
customer.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [77]:
customer.value_counts()

Phillippines  Indonesia   Malta       India     
Error Free    Error Free  Error Free  Error Free    206
Defective     Error Free  Error Free  Error Free     21
Error Free    Defective   Error Free  Error Free     20
              Error Free  Defective   Error Free     18
                          Error Free  Defective      16
              Defective   Defective   Error Free      9
Defective     Error Free  Defective   Error Free      4
              Defective   Error Free  Error Free      2
              Error Free  Error Free  Defective       2
Error Free    Defective   Error Free  Defective       2
dtype: int64

In [80]:
telecall=([[271,267,269,280],[29,33,31,20]])

In [81]:
telecall

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [82]:
stat, p, dof, expected = stats.chi2_contingency(telecall)
print('dof=%d' % dof)
print('p=%f'%p)
print('stat=%f'%stat)
print(expected)

dof=3
p=0.277102
stat=3.858961
[[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


In [83]:
p=0.277102

In [84]:
if p< 0.05:
    print ('A REJECT NULL HYPOTHESIS' )
else:
    
    print( 'WE REJECT TO FAIL NULL HYPOTHESIS')

WE REJECT TO FAIL NULL HYPOTHESIS


#there is no  defective %  varies by centre